# Generated by Django 2.1.5 on 2024-08-12 09:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('CHECKING', 'checking'), ('SAVINGS', 'savings'), ('CASH', 'cash')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(choices=[('General', 'General'), ('Technical', 'Technical'), ('Financial', 'Financial'), ('Other', 'Other')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='contact_images/')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_name', models.CharField(max_length=100)),
                ('budget_type', models.CharField(choices=[('zero_based', 'Zero-Based'), ('fifty_thirty_twenty', '50/30/20')], max_length=20)),
                ('month', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='contact_images/')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('assigned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FiftyThirtyTwentyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(choices=[('Needs', 'Needs'), ('Wants', 'Wants'), ('Savings', 'Savings')], max_length=20)),
                ('is_recurring', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month_only', models.DateField(default=datetime.date(2024, 8, 1))),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifty_thirty_twenty_categories', to='financeapp.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('payee', models.CharField(blank=True, max_length=255, null=True)),
                ('inflow', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('outflow', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by_account', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financeapp.Account')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financeapp.Expense')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeapp.Budget')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZeroBasedCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=100)),
                ('is_recurring', models.BooleanField(default=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zero_based_categories', to='financeapp.Budget')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='financeapp.ZeroBasedCategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='fifty_30_twenty_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='financeapp.FiftyThirtyTwentyCategory'),
        ),
        migrations.AddField(
            model_name='account',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='financeapp.Budget'),
        ),
        migrations.AlterUniqueTogether(
            name='zerobasedcategory',
            unique_together={('budget', 'name', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='fiftythirtytwentycategory',
            unique_together={('budget', 'name', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('category', 'description'), ('fifty_30_twenty_category', 'description')},
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'budget_name')},
        ),
    ]
