# Generated by Django 2.1.5 on 2024-07-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
