# Generated by Django 2.1.5 on 2024-08-12 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0004_auto_20240812_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='month_only',
            field=models.DateField(default=datetime.date(2024, 8, 1)),
        ),
    ]
