# Generated by Django 2.1.5 on 2024-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0006_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='currency_type',
            field=models.CharField(choices=[('POUNDS', 'Pounds'), ('DOLLARS', 'Dollars'), ('EUROS', 'euros')], default='POUNDS', max_length=20),
        ),
    ]
