# Generated by Django 2.1.5 on 2024-08-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0006_auto_20240812_0920'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zerobasedcategory',
            unique_together={('budget', 'name')},
        ),
    ]
