# Generated by Django 2.1.5 on 2024-07-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0009_auto_20240716_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
