# Generated by Django 2.1.5 on 2024-07-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0010_auto_20240716_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
