# Generated by Django 2.1.5 on 2024-08-12 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0012_auto_20240812_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiftythirtytwentycategory',
            name='month_only',
        ),
        migrations.AlterField(
            model_name='fiftythirtytwentycategory',
            name='month',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
