# Generated by Django 2.1.5 on 2024-07-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0012_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_accessed_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeapp.Budget'),
        ),
    ]
