# Generated by Django 2.1.5 on 2024-08-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0012_auto_20240812_1005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fiftythirtytwentycategory',
            unique_together={('budget', 'name', 'month_only')},
        ),
    ]
