# Generated by Django 2.1.5 on 2024-08-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0013_auto_20240812_1302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fiftythirtytwentycategory',
            unique_together={('budget', 'name', 'month')},
        ),
    ]
