# Generated by Django 2.1.5 on 2024-08-12 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0014_fiftythirtytwentycategory_month_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiftythirtytwentycategory',
            name='month',
            field=models.DateField(default=datetime.date(2024, 8, 1)),
        ),
    ]
