# Generated by Django 2.1.5 on 2024-08-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0014_auto_20240812_1303'),
        ('financeapp', '0015_auto_20240812_1507'),
    ]

    operations = [
    ]
