# Generated by Django 2.1.5 on 2024-07-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0015_auto_20240721_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerobasedcategory',
            name='month',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='zerobasedcategory',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.DateField(auto_now_add=True),
        ),
    ]
