# Generated by Django 2.1.5 on 2024-07-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0016_auto_20240722_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.DateField(),
        ),
    ]
