# Generated by Django 2.1.5 on 2024-08-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0016_merge_20240812_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiftythirtytwentycategory',
            name='month_only',
        ),
        migrations.RemoveField(
            model_name='zerobasedcategory',
            name='month_only',
        ),
    ]
