# Generated by Django 2.1.5 on 2024-07-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0017_auto_20240722_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zerobasedcategory',
            name='month',
        ),
        migrations.RemoveField(
            model_name='zerobasedcategory',
            name='year',
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.DateField(auto_now_add=True),
        ),
    ]
