# Generated by Django 2.1.5 on 2024-07-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0018_auto_20240722_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zerobasedcategory',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
