# Generated by Django 2.1.5 on 2024-07-22 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0019_auto_20240722_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerobasedcategory',
            name='month',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
