# Generated by Django 2.1.5 on 2024-08-21 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0019_remove_plaidaccount_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaidaccount',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plaid_account', to='financeapp.Account'),
        ),
    ]
