# Generated by Django 2.1.5 on 2024-07-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0020_zerobasedcategory_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerobasedcategory',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
