# Generated by Django 2.1.5 on 2024-08-21 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0020_plaidaccount_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaidaccount',
            name='account',
        ),
        migrations.DeleteModel(
            name='PlaidAccount',
        ),
    ]
