# Generated by Django 2.1.5 on 2024-08-21 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0021_auto_20240821_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaidAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=100)),
                ('plaid_account_id', models.CharField(max_length=100)),
                ('institution_name', models.CharField(max_length=100)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plaid_account', to='financeapp.Account')),
            ],
        ),
    ]
