# Generated by Django 2.1.5 on 2024-07-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0021_zerobasedcategory_is_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zerobasedcategory',
            name='is_test',
        ),
    ]
