# Generated by Django 2.1.5 on 2024-07-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0023_auto_20240724_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiftythirtytwentybudget',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='fiftythirtytwentycategory',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='fifty_30_twenty_category',
        ),
        migrations.DeleteModel(
            name='FiftyThirtyTwentyBudget',
        ),
        migrations.DeleteModel(
            name='FiftyThirtyTwentyCategory',
        ),
    ]
