# Generated by Django 2.1.5 on 2024-08-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0023_auto_20240822_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'checking'), ('SAVINGS', 'savings'), ('CASH', 'cash')], default='OTHER', max_length=20),
        ),
    ]
