# Generated by Django 2.1.5 on 2024-08-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0024_auto_20240822_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='custom_account_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('CHECKING', 'checking'), ('SAVINGS', 'savings'), ('CASH', 'cash'), ('OTHER', 'other')], default='OTHER', max_length=20),
        ),
    ]
