# Generated by Django 2.1.5 on 2024-07-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0025_auto_20240724_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiftythirtytwentycategory',
            old_name='category',
            new_name='name',
        ),
    ]
