# Generated by Django 2.1.5 on 2024-08-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0027_auto_20240822_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='plaid_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='plaid_imported',
            field=models.BooleanField(default=False),
        ),
    ]
