# Generated by Django 2.1.5 on 2024-07-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0027_auto_20240724_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiftythirtytwentycategory',
            name='is_recurring',
            field=models.BooleanField(default=True),
        ),
    ]
