# Generated by Django 2.1.5 on 2024-08-30 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0028_auto_20240823_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financeapp.Expense'),
        ),
    ]
