# Generated by Django 2.1.5 on 2024-07-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0028_auto_20240724_1456'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fiftythirtytwentybudget',
            unique_together={('budget', 'month')},
        ),
    ]
