# Generated by Django 2.1.5 on 2024-07-25 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0029_auto_20240724_1648'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fiftythirtytwentybudget',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='fiftythirtytwentybudget',
            name='budget',
        ),
        migrations.AddField(
            model_name='fiftythirtytwentycategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiftythirtytwentycategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fiftythirtytwentycategory',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifty_thirty_twenty_categories', to='financeapp.Budget'),
        ),
        migrations.RemoveField(
            model_name='fiftythirtytwentycategory',
            name='is_recurring',
        ),
        migrations.AlterUniqueTogether(
            name='fiftythirtytwentycategory',
            unique_together={('budget', 'name', 'month')},
        ),
        migrations.DeleteModel(
            name='FiftyThirtyTwentyBudget',
        ),
    ]
