# Generated by Django 2.1.5 on 2024-07-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0030_auto_20240725_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiftythirtytwentycategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fiftythirtytwentycategory',
            name='updated_at',
        ),
    ]
