# Generated by Django 2.1.5 on 2024-07-25 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0031_auto_20240725_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiftythirtytwentycategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiftythirtytwentycategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
