# Generated by Django 2.1.5 on 2024-07-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0032_auto_20240725_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiftythirtytwentycategory',
            name='is_recurring',
            field=models.BooleanField(default=True),
        ),
    ]
