# Generated by Django 2.1.5 on 2024-07-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0034_auto_20240727_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiftythirtytwentycategory',
            name='is_user_modified',
        ),
    ]
