# Generated by Django 2.1.5 on 2024-07-28 16:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0035_remove_fiftythirtytwentycategory_is_user_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('payee', models.CharField(blank=True, max_length=255, null=True)),
                ('inflow', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('outflow', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financeapp.Account')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financeapp.Expense')),
            ],
        ),
    ]
