# Generated by Django 2.1.5 on 2024-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0036_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='recurring_income',
            field=models.BooleanField(default=False),
        ),
    ]
