# Generated by Django 2.1.5 on 2024-07-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0037_account_recurring_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='recurring_income',
        ),
    ]
