# Generated by Django 2.1.5 on 2024-07-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0038_remove_account_recurring_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
