# Generated by Django 2.1.5 on 2024-07-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0039_account_previous_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='balance_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
