# Generated by Django 2.1.5 on 2024-08-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0041_auto_20240802_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(max_length=100),
        ),
    ]
