# Generated by Django 2.1.5 on 2024-08-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0042_auto_20240802_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
