# Generated by Django 2.1.5 on 2024-08-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0043_auto_20240802_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='currency_type',
        ),
    ]
