# Generated by Django 2.1.5 on 2024-08-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0044_remove_budget_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerobasedcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
