# Generated by Django 2.1.5 on 2024-08-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0045_auto_20240803_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerobasedcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
