# Generated by Django 2.1.5 on 2024-08-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0046_auto_20240804_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='contact_images/')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
