# Generated by Django 2.1.5 on 2024-08-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0048_accountsupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
