# Generated by Django 2.1.5 on 2024-08-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0049_userprofile_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_name',
            new_name='name',
        ),
    ]
