# Generated by Django 2.1.5 on 2024-08-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0050_auto_20240805_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
