# Generated by Django 2.1.5 on 2024-08-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0051_auto_20240805_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
