# Generated by Django 2.1.5 on 2024-08-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0052_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_by_account',
            field=models.BooleanField(default=False),
        ),
    ]
