# Generated by Django 2.1.5 on 2024-08-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0054_auto_20240806_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='balance_initialized',
        ),
    ]
