# Generated by Django 2.1.5 on 2024-08-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0055_remove_budget_balance_initialized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='previous_balance',
        ),
    ]
