# Generated by Django 2.1.5 on 2024-08-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0056_remove_account_previous_balance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zerobasedcategory',
            unique_together={('budget', 'name', 'month')},
        ),
    ]
