# Generated by Django 2.1.5 on 2024-08-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0057_auto_20240811_1356'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('fifty_30_twenty_category', 'description'), ('category', 'description')},
        ),
    ]
