# Generated by Django 2.1.5 on 2024-08-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0059_auto_20240811_1503'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zerobasedcategory',
            unique_together={('budget', 'name')},
        ),
    ]
