# Generated by Django 2.1.5 on 2024-08-11 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0064_remove_expense_month_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='month_only',
            field=models.DateField(default=datetime.date(2024, 8, 1)),
        ),
        migrations.AddField(
            model_name='fiftythirtytwentycategory',
            name='month_only',
            field=models.DateField(default=datetime.date(2024, 8, 1)),
        ),
        migrations.AddField(
            model_name='zerobasedcategory',
            name='month_only',
            field=models.DateField(default=datetime.date(2024, 8, 1)),
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('category', 'description', 'month_only'), ('fifty_30_twenty_category', 'description', 'month_only')},
        ),
        migrations.AlterUniqueTogether(
            name='fiftythirtytwentycategory',
            unique_together={('budget', 'name', 'month_only')},
        ),
        migrations.AlterUniqueTogether(
            name='zerobasedcategory',
            unique_together={('budget', 'name', 'month_only')},
        ),
    ]
