# Generated by Django 2.1.5 on 2024-08-11 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0066_auto_20240811_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiftythirtytwentycategory',
            name='month_only',
            field=models.DateField(default=datetime.date(2024, 8, 1)),
        ),
    ]
