# # Generated by Django 2.1.5 on 2024-08-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0067_fiftythirtytwentycategory_month_only'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('category', 'description'), ('fifty_30_twenty_category', 'description')},
        ),
    ]
