# Generated by Django 2.1.5 on 2024-08-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0068_auto_20240811_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='month_only',
        ),
        migrations.RemoveField(
            model_name='zerobasedcategory',
            name='month_only',
        ),
    ]
