# Generated by Django 2.1.5 on 2024-08-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0069_auto_20240811_1550'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('category', 'description', 'date'), ('fifty_30_twenty_category', 'description', 'date')},
        ),
    ]
