# Generated by Django 2.1.5 on 2024-08-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0060_auto_20240811_1505'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('category', 'description'), ('fifty_30_twenty_category', 'description')},
        ),
        migrations.AlterUniqueTogether(
            name='fiftythirtytwentycategory',
            unique_together={('budget', 'name', 'month')},
        ),
    ]
