# Generated by Django 2.1.5 on 2024-08-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0062_auto_20240811_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiftythirtytwentycategory',
            name='month_only',
        ),
        migrations.RemoveField(
            model_name='zerobasedcategory',
            name='month_only',
        ),
    ]
