# Generated by Django 2.1.5 on 2024-08-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0063_auto_20240811_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='month_only',
        ),
    ]
